---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kratix
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/syntasso/helm-charts.git"
    path: kratix
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: kratix-platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2
